language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
  - arduino --board arduino:avr:uno --save-prefs
  - arduino --verify $PWD/examples/HDC1000test/HDC1000test.ino
  - arduino --board arduino:sam:arduino_due_x --save-prefs
  - arduino --verify $PWD/examples/HDC1000test/HDC1000test.ino
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --verify $PWD/examples/HDC1000test/HDC1000test.ino
notifications:
  email:
    on_success: change
    on_failure: change
